title: Educational Discounts
url: https://educationaldiscounts.org
permalink: pretty
markdown: kramdown
twitter: _robcerda
github: [metadata]
google_analytics: UA-172004649-1
exclude: 
  - EXCLUSION.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - Gemfile
  - Dockerfile
  - "*.lock"
  - ".*"
  - vendor/
  - scripts/
  - tests/
theme: null
